### ISSUE TITLE
POWER

### ISSUE THREAD

**Issue by nmurolo** [2017-2018-wy-robophins/ftc_app#13]
Make arm power a function of voltage somehow i.e. (if voltage <12) armpower * (12-voltage) but less significant change

Auton arm power is messed up on new phones (direction or something)

Close the rev hub at the end of auton to avoid power surge problems

**Comment by efyang** [comment]
Relevant links:
1: [code](https://github.com/2017-2018-wy-robophins/ftc_app/blob/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainOpMode.java#L72-L76) | [Voltage sensor docs](http://ftckey.com/apis/ftc/index.html?com/qualcomm/robotcore/hardware/VoltageSensor.html)

2: [code](https://github.com/2017-2018-wy-robophins/ftc_app/blob/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutonMain.java#L77-L78)

3: is this even possible?

**Comment by maueroats** [comment]
Urgent: get a power connector compatible with the hub and spice it to get the 12V feed from the main. 

Trying to solve a hardware problem in software is going to be challenging.

If consistency is a still problem, stop other motion when moving. But provide a real voltage feed before deciding this is an issue.

**Comment by maueroats** [comment]
Nico is this still an issue?
Let's look at it Monday and close if not.

**Comment by nmurolo** [comment]
No, it works fine now.
