### ISSUE TITLE
Find current gear ratio of motors

### ISSUE THREAD

**Issue by efyang** [2017-2018-wy-robophins/ftc_app#14]

**Comment by maueroats** [comment]
1:52 for the old motors
new motors we have to choose 1:40 or 1:60
[Motor Specs via FTC 5233](https://chapelgaterobotics.wordpress.com/2014/10/21/neverest-40-motor-v-s-tetrix-max-dc-gear-motor/)

**Comment by maueroats** [comment]
Followup - decide which is more appropriate (torque a little higher) vs (speed a little higher).

**Comment by efyang** [comment]
40:1 chosen.
