### ISSUE TITLE
Refactor move_to_position location

### ISSUE THREAD

**Issue by efyang** [2017-2018-wy-robophins/ftc_app#25]
Would probably be more appropriate if it was part of the robot class itself. Thoughts: potentially have an abstract class which asks for implementation of a movement function (from x,y vector into motor values), and handles the rest based on that function. This would allow easy extensibility to multiple drive bases.

**Comment by maueroats** [comment]
Lots of abstraction probably wasted effort. However - and maybe this is what you said - some kind of Controller class (possibly getting sources of sensor reading when instantiated) seems like a natural way to go if you do go that route.

**Comment by efyang** [comment]
Yeah that's basically what I meant, and it would make a lot of the code reusable even for next year without too many changes.
